# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('eternal_quotex_bot/resources', 'eternal_quotex_bot/resources'), 
        ('eternal_quotex_bot/ui', 'eternal_quotex_bot/ui'),
        ('eternal_quotex_bot/backend', 'eternal_quotex_bot/backend'),
        ('../quotexpy/quotexpy', 'quotexpy'),
        ('../pyquotex/pyquotex', 'pyquotex'),
    ],
    hiddenimports=[
        # Main package and core modules
        'eternal_quotex_bot',
        'eternal_quotex_bot.app',
        'eternal_quotex_bot.controller',
        'eternal_quotex_bot.models',
        'eternal_quotex_bot.settings',
        'eternal_quotex_bot.paths',
        'eternal_quotex_bot.device',
        'eternal_quotex_bot.licensing',
        'eternal_quotex_bot.strategy',
        'eternal_quotex_bot.tick_buffer',
        # UI modules
        'eternal_quotex_bot.ui.main_window',
        'eternal_quotex_bot.ui.license_gate',
        'eternal_quotex_bot.ui.charts',
        'eternal_quotex_bot.ui.glassmorphism_theme',
        'eternal_quotex_bot.ui.alerts',
        'eternal_quotex_bot.ui.theme',
        'eternal_quotex_bot.theme',
        # Backend modules  
        'eternal_quotex_bot.backend.base',
        'eternal_quotex_bot.backend.live',
        'eternal_quotex_bot.backend.external',
        'eternal_quotex_bot.backend.cdm',
        'eternal_quotex_bot.backend.playwright_bridge',
        'eternal_quotex_bot.backend.mock',
        'eternal_quotex_bot.backend.quotexpy_connection',
        # Signal engines
        'eternal_quotex_bot.advanced_signal_engine',
        'eternal_quotex_bot.apex_analysis',
        'eternal_quotex_bot.sniper_scan',
        'eternal_quotex_bot.broadcast_scan',
        'eternal_quotex_bot.visual_signals',
        # Other modules
        'eternal_quotex_bot.automation',
        'eternal_quotex_bot.learning',
        'eternal_quotex_bot.telegram_bot',
        'eternal_quotex_bot.chart_renderer',
        'eternal_quotex_bot.ws_worker_pool',
        'eternal_quotex_bot.pw_price_pool',
        'eternal_quotex_bot.matrix_orchestrator',
        'eternal_quotex_bot.matrix',
        'eternal_quotex_bot.broker_adapters',
        'eternal_quotex_bot.pine_script',
        # Pyquotex library
        'pyquotex',
        'pyquotex.stable_api',
        'pyquotex.api',
        'pyquotex.expiration',
        'pyquotex.config',
        'pyquotex.global_value',
        # QuotexPy library (critical for 25+ pairs streaming)
        'quotexpy',
        'quotexpy.api',
        'quotexpy.http.login',
        'quotexpy.http.logout',
        'quotexpy.http.refresh',
        'quotexpy.http.user_agents',
        'quotexpy.ws.client',
        'quotexpy.ws.channels.ssid',
        'quotexpy.ws.channels.trade',
        'quotexpy.ws.channels.candles',
        'quotexpy.ws.channels.sell_option',
        'quotexpy.ws.objects.candles',
        'quotexpy.ws.objects.profile',
        'quotexpy.ws.objects.timesync',
        'quotexpy.ws.objects.listinfodata',
        'quotexpy.utils',
        'quotexpy.utils.account_type',
        'quotexpy.utils.candles_period',
        'quotexpy.utils.operation_type',
        'quotexpy.utils.asset_parse',
        'quotexpy.exceptions',
        # External libraries - CRITICAL
        'playwright',
        'playwright.async_api',
        'aiohttp',
        'aiohttp.client',
        'websocket',
        'websockets',
        'requests',
        'curl_cffi',
        'curl_cffi.requests',
        'cffi',
        'pkg_resources',
        'pytz',
        # Standard libraries
        'json', 'threading', 'queue', 'asyncio', 
        'urllib.request', 'urllib.error', 'urllib.parse', 
        'dotenv', 'PIL.Image', 'numpy', 'scipy.signal', 'cryptography', 'PySide6'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='EternalQuotexBot_v5',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
